-- DREAM BAKES - Supabase Schema Setup SQL script
-- Copy and paste this script into your Supabase SQL Editor (https://supabase.com dashboard) and click "Run".

-- 1. Create Products Table
CREATE TABLE IF NOT EXISTS public.products (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  rating REAL DEFAULT 5.0,
  reviews INTEGER DEFAULT 0,
  price INTEGER NOT NULL,
  "oldPrice" INTEGER,
  image TEXT,
  description TEXT,
  badge TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS on Products and allow read/write access for all
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access for products" ON public.products FOR SELECT USING (true);
CREATE POLICY "Allow authenticated inserts for products" ON public.products FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow authenticated updates for products" ON public.products FOR UPDATE USING (true);
CREATE POLICY "Allow authenticated deletes for products" ON public.products FOR DELETE USING (true);

-- 2. Create Users (Profiles) Table
CREATE TABLE IF NOT EXISTS public.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  phone TEXT NOT NULL,
  address TEXT DEFAULT '14,2nd Street ,P.Vellalapatti,Karur',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS on Users table and allow all operations (simulated sandbox)
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access for users" ON public.users FOR SELECT USING (true);
CREATE POLICY "Allow public insert access for users" ON public.users FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update access for users" ON public.users FOR UPDATE USING (true);

-- 3. Create Orders Table
CREATE TABLE IF NOT EXISTS public.orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_no TEXT UNIQUE NOT NULL,
  email TEXT,
  name TEXT NOT NULL,
  phone TEXT NOT NULL,
  address TEXT NOT NULL,
  items JSONB NOT NULL,
  subtotal INTEGER NOT NULL,
  shipping INTEGER DEFAULT 0,
  total INTEGER NOT NULL,
  status TEXT DEFAULT 'Pending',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS on Orders and allow insert/select/update
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access for orders" ON public.orders FOR SELECT USING (true);
CREATE POLICY "Allow public insert access for orders" ON public.orders FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update access for orders" ON public.orders FOR UPDATE USING (true);

-- 4. Create Custom Cakes Table
CREATE TABLE IF NOT EXISTS public.custom_cakes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  phone TEXT NOT NULL,
  date TEXT NOT NULL,
  size TEXT NOT NULL,
  flavor TEXT NOT NULL,
  theme TEXT,
  reference_image TEXT,
  status TEXT DEFAULT 'Pending',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS on Custom Cakes
ALTER TABLE public.custom_cakes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access for custom cakes" ON public.custom_cakes FOR SELECT USING (true);
CREATE POLICY "Allow public insert access for custom cakes" ON public.custom_cakes FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update access for custom cakes" ON public.custom_cakes FOR UPDATE USING (true);
